services:

  mysql:
    image: mysql:8.0
    container_name: employee-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: employee-backend
    restart: unless-stopped

    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mysql
      DB_NAME: ${DB_NAME}

    depends_on:
      mysql:
        condition: service_healthy

    expose:
      - "5000"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: employee-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:80"


volumes:
  mysql_data:
